-- 코드를 입력하세요
SELECT 
    RI.REST_ID REST_ID,
    RI.REST_NAME REST_NAME,
    RI.FOOD_TYPE FOOD_TYPE,
    RI.FAVORITES FAVORITES,
    RI.ADDRESS ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) SCORE
FROM REST_INFO RI
JOIN REST_REVIEW RR
    ON RI.REST_ID = RR.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
-- SELECT문을 전부 포함해야 한다(평균 리뷰점수 집계용)
GROUP BY RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS
ORDER BY SCORE DESC, RI.FAVORITES DESC;